import type React from "react"
import { useState } from "react"
import { FormWizard } from "@/components/forms"
import { ProjectSetupForm } from "@/components/forms"
import { useProjectWorkflow } from "@/hooks/useProjectWorkflow"
import type { ProjectCreate, FormulationType } from "@/types/project"
import styles from "@/styles/SPTCalculator.module.css"

interface ProjectFormData {
  project_name: string;
  number_of_boreholes: number;
  number_of_strata: number;
  formulation: FormulationType;
}

const SPTCalculator: React.FC = () => {
  const {
    steps,
    projectData,
    strataData,
    boreholesData,
    loading,
    submitProjectData,
  } = useProjectWorkflow();

  // Store form data for validation, but don't submit yet.

  const [currentFormData, setCurrentFormData] = useState<ProjectFormData | null>(null);
  const [isFormValid, setIsFormValid] = useState(false);

  const handleProjectDataChange = (data: ProjectFormData, isValid: boolean) => {
    // Store the form data and validation state, but don't submit to API yet
    setCurrentFormData(data);
    setIsFormValid(isValid);
    console.log('Form data updated:', data, 'Valid:', isValid);
  };

  // This function will be called when the "Next" button is clicked
  const handleProjectSubmit = async () => {
    if (!isFormValid || !currentFormData) {
      console.error('Form data not valid or missing');
      return;
    }

    try {
      // Transform form data to match ProjectCreate interface
      // Note: project_code is auto-generated by backend
      const projectCreateData: ProjectCreate = {
        project_name: currentFormData.project_name,
        number_of_boreholes: currentFormData.number_of_boreholes,
        number_of_strata: currentFormData.number_of_strata,
        formulation: currentFormData.formulation,
        // project_code is auto-generated by backend
      };
      
      const result = await submitProjectData(projectCreateData);
      console.log('Project submitted successfully!', result);
      return result; // Return the result for further processing
    } catch (error) {
      console.error('Failed to create project:', error);
      throw error; // Re-throw to prevent navigation
    }
  };

  // Handle step navigation with API calls
  const handleStepNext = async (stepIndex: number) => {
    try {
      if (stepIndex === 0) {
        // Step 1: Submit project data when leaving this step
        const result = await handleProjectSubmit();
        if (result) {
          console.log('Project created successfully, proceeding to next step');
        }
      }
      // Add more step handlers here for steps 2-4
      // if (stepIndex === 1) await handleStrataSubmit();
      // if (stepIndex === 2) await handleBoreholesSubmit();
      // etc.
      
      console.log(`Step ${stepIndex} completed successfully`);
      // Navigation will be handled by FormWizard after this function returns successfully
    } catch (error) {
      console.error('Failed to submit step data:', error);
      throw error; // Re-throw to prevent navigation
    }
  };

  const handleWizardComplete = async () => {
    // This gets called on the final step
    console.log('Workflow complete - ready for results analysis');
  };

  const wizardSteps = [
    {
      id: "project-setup",
      title: "Formulario base",

      component: (
        <ProjectSetupForm
          initialData={undefined}
          onValidData={handleProjectDataChange}
        />
      ),
      isValid: isFormValid
    },
    
    {
      id: "strata-definition",
      title: "Definir estratos",
      description: "Define soil layers and their geotechnical properties",
      component: (
        <div className={styles.placeholderStep}>
          <p className={styles.placeholderTitle}>Strata Definition Form</p>
          <p className={styles.placeholderDescription}>
            Create {projectData?.number_of_strata || 0} soil strata with gamma values
          </p>
          {projectData && (
            <div style={{ marginTop: '20px', padding: '15px', background: '#f0f9ff', borderRadius: '8px', border: '1px solid #0ea5e9' }}>
              <h4 style={{ margin: '0 0 10px 0', color: '#0369a1' }}>✅ Project Created Successfully!</h4>
              <p><strong>Project Code:</strong> {projectData.project_code}</p>
              <p><strong>Required Strata:</strong> {projectData.number_of_strata}</p>
              <p><strong>Formulation:</strong> {projectData.formulation}</p>
              <p style={{ marginTop: '10px', fontSize: '14px', color: '#0369a1' }}>
                <strong>Next:</strong> Create {projectData.number_of_strata} soil strata definitions
              </p>
            </div>
          )}
        </div>
      ),
      isValid: steps[1].completed
    },
    {
      id: "borehole-creation",
      title: "Crear perforaciones",
      description: "Create boreholes with locations and depths",
      component: (
        <div className={styles.placeholderStep}>
          <p className={styles.placeholderTitle}>Borehole Creation Form</p>
          <p className={styles.placeholderDescription}>
            Create {projectData?.number_of_boreholes || 0} boreholes (auto-named P1, P2, P3...)
          </p>
          {projectData && strataData.length > 0 && (
            <div style={{ marginTop: '20px', padding: '15px', background: '#f0fdf4', borderRadius: '8px', border: '1px solid #22c55e' }}>
              <h4 style={{ margin: '0 0 10px 0', color: '#15803d' }}>✅ Strata Created Successfully!</h4>
              <p><strong>Project:</strong> {projectData.project_code}</p>
              <p><strong>Required Boreholes:</strong> {projectData.number_of_boreholes}</p>
              <p><strong>Strata Created:</strong> {strataData.length}</p>
              <p style={{ marginTop: '10px', fontSize: '14px', color: '#15803d' }}>
                <strong>Next:</strong> Create {projectData.number_of_boreholes} borehole locations
              </p>
            </div>
          )}
        </div>
      ),
      isValid: steps[2].completed
    },
    {
      id: "spt-intervals",
      title: "Datos de intervalos SPT",
      description: "Input SPT test results for each borehole interval",
      component: (
        <div className={styles.placeholderStep}>
          <p className={styles.placeholderTitle}>SPT Intervals Data Form</p>
          <p className={styles.placeholderDescription}>
            Add SPT N-values for each depth interval in all boreholes
          </p>
          {boreholesData.length > 0 && (
            <div style={{ marginTop: '20px', padding: '15px', background: '#fefce8', borderRadius: '8px', border: '1px solid #eab308' }}>
              <h4 style={{ margin: '0 0 10px 0', color: '#a16207' }}>✅ Boreholes Created Successfully!</h4>
              <p><strong>Boreholes Created:</strong> {boreholesData.length}</p>
              <p><strong>Names:</strong> {boreholesData.map(b => b.borehole_name || `P${b.id}`).join(', ')}</p>
              <p style={{ marginTop: '10px', fontSize: '14px', color: '#a16207' }}>
                <strong>Next:</strong> Add SPT test data for each borehole interval
              </p>
            </div>
          )}
        </div>
      ),
      isValid: steps[3].completed
    },
    {
      id: "results",
      title: "Resultados y análisis",
      description: "View calculated geotechnical parameters and generate reports",
      component: (
        <div className={styles.placeholderStep}>
          <p className={styles.placeholderTitle}>Results and Analysis</p>
          <p className={styles.placeholderDescription}>
            Calculated SPT parameters, charts, and final report generation
          </p>
          {steps[4].completed && (
            <div style={{ marginTop: '20px', padding: '15px', background: '#f0fdf4', borderRadius: '8px', border: '1px solid #22c55e' }}>
              <h4 style={{ margin: '0 0 10px 0', color: '#15803d' }}>🎉 Project Complete!</h4>
              <p><strong>All data processed successfully!</strong></p>
              <p>SPT calculations ready for analysis and visualization.</p>
            </div>
          )}
        </div>
      ),
      isValid: steps[4].completed
    }
  ];

  return (
    <div className={styles.page}>
      <div className={styles.container}>
        <div className={styles.header}>
          <p className={styles.subtitle}>Generador de parametros &#964; y &#966;</p>
        </div>


        {loading && (
          <div className={styles.loadingOverlay}>
            <div className={styles.loadingModal}>
              <div className={styles.loadingSpinner}></div>
              <p className={styles.loadingText}>Processing API request...</p>
            </div>
          </div>
        )}

        <FormWizard
          steps={wizardSteps}
          onComplete={handleWizardComplete}
          onStepNext={handleStepNext}
        />
      </div>
    </div>
  )
}

export default SPTCalculator
