"""initial_migration_sqlite

Revision ID: 14cc2f4e6505
Revises: 
Create Date: 2025-11-26 11:21:20.679634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cc2f4e6505'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('project_code', sa.String(), nullable=False),
    sa.Column('number_of_boreholes', sa.Integer(), nullable=False),
    sa.Column('number_of_strata', sa.Integer(), nullable=False),
    sa.Column('formulation', sa.Enum('KISHIDA', 'JRB', name='formulationtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_table('boreholes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('borehole_name', sa.String(), nullable=False),
    sa.Column('final_depth', sa.Float(), nullable=False),
    sa.Column('diameter_mm', sa.Float(), nullable=False),
    sa.Column('field_energy_percent', sa.Float(), nullable=False),
    sa.Column('water_table_depth', sa.Float(), nullable=True),
    sa.Column('formulation', sa.Enum('KISHIDA', 'JRB', name='formulationtype'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boreholes_id'), 'boreholes', ['id'], unique=False)
    op.create_table('stratum_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stratum_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('gamma_humid', sa.Float(), nullable=False),
    sa.Column('gamma_saturated', sa.Float(), nullable=False),
    sa.Column('behavior_type', sa.Enum('COHESIVE', 'GRANULAR', name='behaviortype'), nullable=False),
    sa.Column('plasticity_index', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stratum_definitions_id'), 'stratum_definitions', ['id'], unique=False)
    op.create_table('borehole_strata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borehole_id', sa.Integer(), nullable=False),
    sa.Column('stratum_definition_id', sa.Integer(), nullable=False),
    sa.Column('stratum_code', sa.String(), nullable=False),
    sa.Column('initial_depth', sa.Float(), nullable=False),
    sa.Column('final_depth', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['borehole_id'], ['boreholes.id'], ),
    sa.ForeignKeyConstraint(['stratum_definition_id'], ['stratum_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borehole_strata_id'), 'borehole_strata', ['id'], unique=False)
    op.create_table('spt_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borehole_id', sa.Integer(), nullable=False),
    sa.Column('borehole_stratum_id', sa.Integer(), nullable=False),
    sa.Column('depth_from', sa.Float(), nullable=False),
    sa.Column('depth_to', sa.Float(), nullable=False),
    sa.Column('midpoint_depth', sa.Float(), nullable=False),
    sa.Column('nspt_field', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['borehole_id'], ['boreholes.id'], ),
    sa.ForeignKeyConstraint(['borehole_stratum_id'], ['borehole_strata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spt_intervals_id'), 'spt_intervals', ['id'], unique=False)
    op.create_table('calculated_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spt_interval_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('borehole_id', sa.Integer(), nullable=True),
    sa.Column('borehole_name', sa.String(), nullable=True),
    sa.Column('stratum_code', sa.String(), nullable=True),
    sa.Column('sigma_prime', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cb_factor', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('cs_factor', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('cr_factor', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('cn_factor', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('n45', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('n55', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('n60', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('n145', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('phi_prime_eq', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('elastic_modulus', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tau_resistance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('su_undrained', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['borehole_id'], ['boreholes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['spt_interval_id'], ['spt_intervals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spt_interval_id')
    )
    op.create_index(op.f('ix_calculated_results_borehole_name'), 'calculated_results', ['borehole_name'], unique=False)
    op.create_index(op.f('ix_calculated_results_id'), 'calculated_results', ['id'], unique=False)
    op.create_index(op.f('ix_calculated_results_stratum_code'), 'calculated_results', ['stratum_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculated_results_stratum_code'), table_name='calculated_results')
    op.drop_index(op.f('ix_calculated_results_id'), table_name='calculated_results')
    op.drop_index(op.f('ix_calculated_results_borehole_name'), table_name='calculated_results')
    op.drop_table('calculated_results')
    op.drop_index(op.f('ix_spt_intervals_id'), table_name='spt_intervals')
    op.drop_table('spt_intervals')
    op.drop_index(op.f('ix_borehole_strata_id'), table_name='borehole_strata')
    op.drop_table('borehole_strata')
    op.drop_index(op.f('ix_stratum_definitions_id'), table_name='stratum_definitions')
    op.drop_table('stratum_definitions')
    op.drop_index(op.f('ix_boreholes_id'), table_name='boreholes')
    op.drop_table('boreholes')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
